project:
  type: book
  output-dir: docs

book: 
  #reader-mode: true
  page-navigation: true
  title: "Registre parcellaire graphique"
  subtitle: "(RPG)"
  author: 
    - name: "Alain CORVISIER"
      email: alain.corvisier@proton.me
  sidebar:
    style: docked
    background: light
  repo-url: https://github.com/a-lambda/rpg
  repo-actions: [edit]
  search: true
  chapters:
    - index.qmd
    - intro.qmd
    - href: rpg_2022.qmd
      text: Données RPG 2022
    - href: rpg_leaflet.qmd
      text: Données RPG commune aléatoire
      
bibliography: references.bib
  
format:
  html:
    cover-image: images/cover.png
    theme: 
      light:
        - cosmo
        - css/fira-code.css
        - css/light.css
      dark:
        - slate
        - css/dark.css
    code-overflow: wrap
    code-link: true
    # code-block-bg: inactive due to $code-block-bg definition
    code-block-border-left: "#31BAE9"
    code-tools: 
      source: true
      toggle: false # A quoi sert cette option ?
      caption: none
    toc: true
    mainfont: Arial
    monofont: Fira Code
    fontsize: 0.9em
    number-depth: 3
