project:
  type: book
  output-dir: docs

book:
  #reader-mode: true
  page-navigation: true
  title: "Registre parcellaire graphique"
  subtitle: "(RPG)"
  author: 
    - name: "Alain CORVISIER"
      email: alain.corvisier@proton.me
  sidebar:
    style: floating
    background: "#FFFFFF" # "#A804FF15"
    foreground: "#000000"

  site-url: https://www.chapelier-fou.fr/rpg/
  repo-url: https://github.com/a-lambda/rpg/
  repo-branch: main
  repo-actions: [edit, source]
  search: true
  chapters:
    - index.qmd
    - href: rpg_2022.qmd
      text: Données RPG 2022
    - href: rpg_leaflet.qmd
      text: Données RPG commune aléatoire
      
bibliography: references.bib
  
format:
  html:
    grid:
      sidebar-width: 250px
      body-width: 1000px
      margin-width: 250px
      gutter-width: 1.5rem
    page-layout: full
    lang: "fr"
    cover-image: images/cover.png
    theme: 
      light:
        - cosmo
        - css/open-sans.css
        - css/gabarito.css
        - css/fira-code.css
        - css/light.css
      dark:
        - slate
    code-overflow: wrap
    code-link: true
    code-block-bg: "#C0C0E018" # "#FFFF2010" inactive if css $code-block-bg defined
    code-block-border-left: "#40CAFF60"  # "#31BAE9"
    code-tools: 
      source: true
      toggle: false # A quoi sert cette option ?
      caption: none
    toc: true
    mainfont: Open Sans
    monofont: Fira Code
    # fontsize: 1em # dégrade la qualité de la police du code
    number-depth: 3
  pdf:
    documentclass: scrreport