project:
  type: book
  output-dir: docs

book:
  #reader-mode: true
  page-navigation: true
  title: "Registre parcellaire graphique"
  subtitle: "(RPG)"
  author: 
    - name: "Alain CORVISIER"
      email: alain.corvisier@proton.me
  sidebar:
    style: docked
    background: "#A804FF20"
    foreground: "#000000"

  site-url: https://www.chapelier-fou.fr/rpg/
  repo-url: https://github.com/a-lambda/rpg/
  repo-branch: main
  repo-actions: [edit, source]
  search: true
  chapters:
    - index.qmd
    - intro.qmd
    - href: rpg_2022.qmd
      text: Données RPG 2022
    - href: rpg_leaflet.qmd
      text: Données RPG commune aléatoire
      
bibliography: references.bib
  
format:
  html:
    lang: "fr"
    cover-image: images/cover.png
    theme: 
      light:
        - cosmo
        - css/fira-code.css
        - css/light.css
      dark:
        - slate
    code-overflow: wrap
    code-link: true
    code-block-bg: "#FFFF2010"         # inactive if css $code-block-bg defined
    code-block-border-left: "#40CAF9"  # "#31BAE9"
    code-tools: 
      source: true
      toggle: false # A quoi sert cette option ?
      caption: none
    toc: true
    mainfont: Consolas
    monofont: Fira Code
    fontsize: 0.9em
    number-depth: 3
  pdf:
    documentclass: scrreport