---
title: "leaflet"
format: html
---

## Récupération des données rpg pour une commune aléatoire des Hauts-de-France

```{r}
#| label: load_libraries
#| echo: false
#| message: false
#| warning: false

library(leaflet)
library(sf)
library(dplyr)
library(ggplot2)
library(data.table)
# library(oceanis)

# https://geoservices.ign.fr/documentation/donnees/vecteur/rpg

```

### Récupération des données relatives aux cultures

```{r}
#| label: charge_ref_nomenclature
#| echo: false

# je charge la nomenclature de référence
file_ref <- "DATA/REFERENCES/REF_CULTURES_GROUPES_CULTURES_2021.csv"
data_ref_culture = data.table::fread(file_ref) |> 
  dplyr::select(CODE_CULTURE, LIBELLE_CULTURE)

```

### Récupération des limites communales d'OpenStreetMap au 1er janvier 2022 

```{r}
#| label: limites_communales_HDF

limites_communales <- readRDS("DATA/OSM/sf_2022_limites_communes.RDS")

limites_communales_HDF <- limites_communales |> 
  dplyr::filter(substr(insee, 1, 2) %in% c("02", "59", "60", "62", "80"))

codes_insee <- limites_communales_HDF$insee 

```

### Chargement des données RPG des Hauts de France

```{r}
#| label: load_shp_HDF
#| output: false
#| message: false
#| warning: false

data_rpg_geo_HDF <- sf::st_read("DATA/RPG_2-0__SHP_LAMB93_R32_2022-01-01/PARCELLES_GRAPHIQUES.shp")

data_rpg_geo_HDF_code_cultu <- data_rpg_geo_HDF |> 
  dplyr::select(CODE_CULTU) |> 
  dplyr::left_join(data_ref_culture, by = dplyr::join_by(CODE_CULTU == CODE_CULTURE))

```

### Sélection aléatoire d'une commune et affichage des données RPG associées

```{r}
#| label: choix_aleatoire_commune_HDF
#| warning: false

code_insee = sample(codes_insee, 1)
commune <- limites_communales_HDF |> 
  dplyr::filter(insee == code_insee)

commune_geo <- sf::st_geometry(commune)
zone_lambert <- sf::st_transform(commune_geo, crs = "EPSG:2154")
inter_2154 <- sf::st_intersection(data_rpg_geo_HDF_code_cultu, zone_lambert)

inter_wgs84 <- sf::st_transform(inter_2154, crs = "EPSG:4326")

ggplot() + 
  ggplot2::geom_sf(data = inter_wgs84, aes(fill = CODE_CULTU)) +
  ggplot2::labs(
    title = paste("Commune :", commune$nom)
  ) +
  ggplot2::coord_sf(expand = TRUE) +
  theme(
    panel.background = element_rect(fill = "transparent", color = NA),
    plot.background = element_rect(fill = "transparent", color = NA),
    panel.grid.major = element_line(linewidth = 0.1, color = "black", linetype = "dashed"),
    title = element_text(color = "black")
  )

pal <- colorFactor(palette = "YlOrRd", domain = inter_wgs84$CODE_CULTU)
leaflet(inter_wgs84) |> 
  leaflet::addTiles() |> 
  leaflet::addPolygons(color = NA, 
              fillColor = ~ pal(CODE_CULTU), 
              fillOpacity = 0.5,
              popup = ~paste(LIBELLE_CULTURE, CODE_CULTU)) |> 
  leaflet::addLegend(pal = pal, values = ~ CODE_CULTU, opacity = 0.5)

```

